src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrderItemRepository::class)]
#[ORM\Table(name: '`order_item`')]
class OrderItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $offer = null;

    #[ORM\Column(type: 'uuid', nullable: true)]
    private ?Uuid $ticket = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $orderRef = null;

    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }

    public function getTotal(): float
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOffer(): ?string
    {
        return $this->offer;
    }

    public function setOffer(?string $offer): static
    {
        $this->offer = $offer;

        return $this;
    }

    public function getTicket(): ?Uuid
    {
        return $this->ticket;
    }
    
    public function setTicket(?Uuid $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function generateTicket()
    {
            $this->setTicket(Uuid::v4());
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): static
    {
        $this->orderRef = $orderRef;

        return $this;
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class,
            ])
            ->add('clear', SubmitType::class);

            $builder->addEventSubscriber(new RemoveCartItemListener());
            $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Manager\CartManager;
use App\Form\CartType;
use App\Utils\MockPaymentServer;
use App\Service\QrCodeGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Cookie;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'app_cart')]
    public function index(
        CartManager $cartManager,
        Security $security,
        Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);

        $oldCarts = null;
        if ($security->isGranted('IS_AUTHENTICATED')) {
            $oldCarts = $security->getUser()->getOldOrders();
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->save($cart);
        
            return $this->redirectToRoute('app_cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView(),
            'oldCarts' => $oldCarts,
        ]);
    }

    #[Route('/paiement', name: 'app_checkout')]
    public function checkout(
        Request $request,
        CartManager $cartManager,
        MockPaymentServer $paymentServer,
        Security $security,
        QrCodeGenerator $qrCodeGenerator)
    {
        if ($security->isGranted('IS_AUTHENTICATED')) {
            $paymentResponse = $paymentServer->handleRequest();

            if ($paymentResponse->getStatusCode() === 200) {
                $qrCodeGenerator->generateQrCode();
                $cartManager->validateCart();
                $this->addFlash('success', 'Paiement réussi.');
            }

            else {
                $this->addFlash('danger', 'Echec du paiement, veuillez réessayer.');
            }    

            return $this->redirectToRoute('app_cart');
        }

        else {
            $response = new Response();
            $response->headers->setCookie(new Cookie('checkout', true, time() + 3600 * 24 * 30, '/', '', false, true));
            $response->setStatusCode(302);
            $response->headers->set('Location', $this->generateUrl('app_login'));
            return $response;
        }
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }}">{{ message }}</div>
        {% endfor %}
    {% endfor %}
    <div class="container mt-4">
        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- Cart items -->
                <div class="col-md-8">
                    {{ form_start(form) }}
                    <div class="card">
                        <div class="card-header bg-dark text-white d-flex">
                            <h5>Votre Panier</h5>
                            <div class="ml-auto">
                                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for item in form.items %}
                                <li class="list-group-item item-in-cart d-flex align-items-center">
                                    <div class="col-md-2 pl-0">
                                        <img src="{{ asset('images/product/' ~ item.vars.data.product.id ~ '.png') }}" width="110">
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-12 mb-2">
                                                <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }} </h5>
                                                <small>{{ item.vars.data.product.datetime|date('d/m/Y H:i') }} ({{ item.vars.data.quantity }} pers.)</small>
                                            </div>
                                            <div class="col-md-12">
                                                {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 text-right">
                                        <b>{{ (item.vars.data.product.price * item.vars.data.quantity) }} €</b>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {{ form_end(form) }}
                </div>
                <!-- Summary -->
                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h5 class="card-header bg-dark text-white"></h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>{{ cart.total }} €</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="{{ path('app_checkout') }}" class="btn btn-warning w-100">Paiement</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                Votre panier est vide. Aller à la <a href="{{ path('shop') }}">boutique</a>.
            </div>
        {% endif %}
    </div>

    <div class="container mt-4">
        {% if oldCarts|length > 0 %}
            <!-- Concluded purchases -->
            <div class="row mt-4">
                <div class="col-md-8">
                    <hr class="mb-4">
                    <div class="card-header bg-dark text-white d-flex">
                        <h5>Historique d'achat</h5>
                    </div>
                    {% for oldCart in oldCarts %}
                        <div class="card mb-4">
                            <div class="card-header bg-light text-muted py-1">
                                <small>{{ oldCart.date }} - Total: {{ oldCart.total }} €</small>
                            </div>
                            <ul class="list-group list-group-flush">
                                {% for item in oldCart.items %}
                                    <li class="list-group-item">
                                        <div class="d-flex">
                                            <div class="flex-fill mr-2">
                                            </div>
                                            <div class="flex-fill mr-2">
                                                <h5 class="mt-0 mb-0">{{ item.name }}</h5>
                                                <small>{{ item.datetime|date('d/m/Y H:i') }}</small></br>
                                                <small>Entrée pour {{ item.quantity }} personne(s)</small>
                                            </div>
                                            <div class="flex-fill mr-2 text-right">
                                            </div>
                                            <div class="flex-fill mr-2">
                                                    <img src="{{ asset('images/qrcode/' ~ item.ticket ~ '.png') }}" width="64" alt="QR Code">
                                                    <a href="{{ asset('images/qrcode/' ~ item.ticket ~ '.png') }}" download="qrcode_{{ item.ticket }}.png">
                                                        <button type="button" class="btn btn-primary btn-xs" style="font-size: 0.8em;">Télécharger</button>
                                                    </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>

                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}